# Generated by Django 3.2.18 on 2023-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('tagline', models.CharField(max_length=100)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=50, null=True)),
                ('runtime', models.IntegerField()),
            ],
        ),
    ]
